service: finnhub-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    CONNECTION_DB_TABLE: ${self:resources.Resources.FinnhubApiWsConnectionTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:PutItem'
        - 'dynamodb:GetItem'
        - 'dynamodb:DeleteItem'
        - 'dynamodb:Scan'
      Resource:
        - Fn::GetAtt: [FinnhubApiWsConnectionTable, Arn]
    - Effect: Allow
      Action:
        - 'execute-api:ManageConnections'
      Resource:
        - 'arn:aws:execute-api:*:*:**/@connections/*'
  websocketsApiName: ${self:service}-ws
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Finnhub Websocket API
  logs:
    websocket: true

functions:
  connectHandler:
    handler: handler.connectHandler
    events:
      - websocket:
          route: $connect
  disconnectHandler:
    handler: handler.disconnectHandler
    events:
      - websocket:
          route: $disconnect
  defaultHandler:
    handler: handler.defaultHandler
    events:
      - websocket:
          route: $default
  broadcastHandler:
    handler: handler.broadcastHandler
    events:
      - websocket:
          route: broadcastMessage

resources:
  Resources:
    FinnhubApiWsConnectionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: FinnhubApiWsConnectionTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: 'connectionId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'connectionId'
            KeyType: 'HASH'
